### ISSUE TITLE
ArrayOutOfBoundsException in viewing tweets? D:

### ISSUE THREAD

**Issue by MidnaPeach** [dai1313/SuperheroTwitter#13]
I'm getting this when I try to view stuff. I feel like I did something wrong because Tyler said it was working on his machine. :< ??

![screenshot from 2015-04-15 03 33 50](https://cloud.githubusercontent.com/assets/11181794/7154088/5e7d6f8e-e320-11e4-99a3-a54ce4008273.png)
![screenshot from 2015-04-15 03 33 30](https://cloud.githubusercontent.com/assets/11181794/7154087/5e7d2f2e-e320-11e4-9f83-a5290e9f2dc1.png)

**Comment by dai1313** [comment]
Check your .dat files for shenanagans,

**Comment by MidnaPeach** [comment]
I'm honestly not even sure what the .dat files are supposed to look like. Can you explain them?

**Comment by dai1313** [comment]
Can you post yours?

**Comment by MidnaPeach** [comment]
Actually, I think I did commit my users file the last time. Do you see it there?

I'll commit both of them now.
