### ISSUE TITLE
No file i/o

### ISSUE THREAD

**Issue by dai1313** [dai1313/SuperheroTwitter#2]
So, we haven't decided on the syntax to write the tweet file or the user file

I tentatively propose this...

author body public tags 
author body public tags 
author body public tags 

for tweet, we may also want to include a timestamp

for users I propose

user password following1,following2,following3 bio
user password following1,following2,following3 bio
user password following1,following2,following3 bio 

we have some time to figure this out though, and most of the I/O is going to be handled by the string constructor and the toString method so no worries.

If anyone has any suggestions about how to store passwords without displaying them in plaintext that would be super cool

even if we just impliment a simple Ovaltine style shift cypher that would be super cool and we could say that our code is more secure against villainous attacks.

**Comment by MidnaPeach** [comment]
Wait, did you figure this out?

I love the Ovaltine reference. And are we going to be printing out the passwords to the screen every time in the final version? I don't think it's so bad if we end up needing to store it like that in the files.

**Comment by dai1313** [comment]
No, in the final version passwords will not be printed to the screen. Right now i'm still  doing debugging.

**Comment by MidnaPeach** [comment]
That's what I was thinking. :)
