### ISSUE TITLE
Small Bug- line printing that shouldn't?

### ISSUE THREAD

**Issue by MidnaPeach** [dai1313/SuperheroTwitter#9]
Hey so I noticed that the line "could not find username" is printing after I quit the Lookup/Follow User menu.

Didn't want to mess up your beautiful menus so I just thought I'd post on here instead. Let me know if you'd rather I look into it.

Not sure if this is the only occurrence.

![image](https://cloud.githubusercontent.com/assets/11181794/7107641/5c554aa8-e139-11e4-9fdf-f10601e93e86.png)

**Comment by dai1313** [comment]
Ah, I see the bug. I can fix this no problem.

**Comment by dai1313** [comment]
OK, I pushed a fix but didn't really test it. If it works we can close the issue.

**Comment by MidnaPeach** [comment]
Okay! Sounds good. I'll let you know when I've tested it!
